# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f10e9564f25312d0a818780bbc58d23f4c2c0e58a1c55be2ff0e54c8167102f2227fff21307dc61078eca5f0ebb317e1fd0f9f2f126e094061e8f4be234472d9

test:
  secret_key_base: 11e9e09ee440fc7d8b7933e9abf0a4cfc33826cb3272ce314377257333e8867df70cfc3e8da447eafc41bd81ded96f20932d288ab3a9322dee0821dc9da24243

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
